/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leo_ndkdemo_JniTestUtil */

#ifndef _Included_com_leo_ndkdemo_JniTestUtil
#define _Included_com_leo_ndkdemo_JniTestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leo_ndkdemo_JniTestUtil
 * Method:    getHelloStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leo_ndkdemo_JniTestUtil_getHelloStr
  (JNIEnv *, jclass);

/*
 * Class:     com_leo_ndkdemo_JniTestUtil
 * Method:    getHelloStr2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leo_ndkdemo_JniTestUtil_getHelloStr2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
